### ISSUE TITLE
Loading pretrained model when features change

### ISSUE THREAD

**Issue by mangleddata** [ludwig-ai/ludwig#1028]
I had previously opened https://github.com/uber/ludwig/issues/1009 (resolved now, thanks!) - but found the following behaviour.

Run 1: Have features_{0..100} and have a trained model.
Run 2: I now have a new feature feature_101 added to the same data set and have the new features added to the model file (all else being the same). Essentially added one more column. Now using the pretrained model in run 1 for run 2 still seems to run - but from what I could tell, it drops the newly added feature (I don't see the feature in the input_features array in description.json)

Is this expected ?

**Comment by w4nderlust** [comment]
Yes, right now there is no mechanism in Ludwig to load a model trained with a different model definition (even if only different by one feature) as a starting point for another model.
What happens in your case is that the model definition of the model you are loading is what ends up being used instead.
So yes, this is expected behavior right now.

I guess we can turn this into a feature request.
If I understand correctly (please confimr) what you would like to happen here is that you would want to load the pieces of the previous model that match with the new model definition ( encoders of feature 0-100 and decoder of the output feature) and randomly initialize the parts that don't match(encoder of feature 101 and the combiner).
This is interesting and something we may consider in the future.

**Comment by mangleddata** [comment]
What you wrote is exactly what I wanted to do! Thanks for considering the feature request.

**Comment by jenishah** [comment]
We can use `model.get_weights()` and `model.set_weights()` to keep the previous weights for the new model. This can be used if the architecture does not change, but only the number of hidden units.  
@w4nderlust, if you think this can be used, please let me know.  I would like to work on this.

**Comment by w4nderlust** [comment]
@jenishah thanks! Yes we can do that, the issue are some layers that may end up being different depending on the architecture, so there needs to be something like a check that figures out for ech encoder combiner and decoder if the name match and if the size matches and only in that case load the weights and communicate with modules have ben loaded and which have not been loaded.

**Comment by jenishah** [comment]
@w4nderlust will include these factors while iterating. Thanks!

**Comment by camaya7** [comment]
Hi @jenishah, thanks for posting your tip. This is a bit outdated but do you happen to remember where `model.get_weights()`and `model.set_weights()` can be modified? I'm having trouble finding them. 

@w4nderlust thank you for such amazing attention to your users! Any guidance on how to transfer trained model weights to a new model with a new dataset's model definition?

Thanks in advance.

**Comment by w4nderlust** [comment]
@camaya7 we are working right now on this feature. @dantreiman is mostly involved.
The interface e are thinking about looks like:
`my_model.load_weights(pretrained_model_path_or_loaded_model, feature_mappings)`
where `feature_mappings` is used for saying that, for instance, the encoder of feature X from the pretrained model should be used as the encoder of feature Y in `my_model`.
Will keep you posted on the progress, as we are working on it right now.

**Comment by camaya7** [comment]
@w4nderlust thanks for the prompt response man. @dantreiman 's work looks very interesting, I look forward to seeing the solution here. I'll probably have some questions with regards to the variable inputs and CLI implementation (if that's not too demanding for this feature.)

Either way thank you for the effort and update as I know this feature involves a bit of digging and refactoring.

Cheers.

**Comment by w4nderlust** [comment]
@camaya7 for CLI and in general config base we are thinking about providing something like:
```
input_features:
  - name: my_feature
     type: whatever
    encoder: path_to_pretrained_model/input_features/specific_feature
```
Would that work for you?

**Comment by camaya7** [comment]
@w4nderlust Looks good overall. Only thing-- how would I go about selecting `input_features/specific_feature` from the `path_to_pretrained_model` ?

**Comment by w4nderlust** [comment]
@w4nderlust we are still determining it, but let's assume you have a model `email_sentiment` that classifies the sentiment of email texts with only one input feature called message (text). And then you have an `email_spam_classifier` to classify spam emails, say, and you have 3 inputs: subject (text), body (text), sender (category). To reuse the sentiment encoder you would so something like
```
email_spam_classifier.yaml

input_features:
  - name: body
    type: text
    encoder: /home/camaya7/email_sentiment/input_features/message
```
or there could be a different separator instead of `/`, something like `/home/camaya7/email_sentiment#input_features#message`, not sure yet, the important thing is specifying in this case which encoder from which input feature of which pretrained model you want to use to initialize your weights

**Comment by camaya7** [comment]
@w4nderlust Good example you used, it's understood for the most part. The section I'm not getting is what the input_features file is-- Is it a file produced from training the original model/original learning?

**Comment by w4nderlust** [comment]
@camaya7 there's no file, it's just a naming scheme to refer to parts of a pretrained model, in this case, the weights of the encoder of a specific input feature

**Comment by camaya7** [comment]
@w4nderlust Understood, those were my initial thoughts but I had my doubts in the fact that `/home/camaya7/email_sentiment/input_features/message` appears to be a file path. 

I would think that using the # in `/home/camaya7/email_sentiment#input_features#message` could work as a better way to reference the elements within the `email_sentiment` file. Also, wouldn't it make sense to have the original learner's weights passed on to the transfer learner's config using something like `/home/camaya7/results/email_sentiment/model/model_weights` as input to be included in the transfer learner's config file, where, `email_sentiment/model/model_weights` is the output Zip archive weight data from the original learner model training?

**Comment by w4nderlust** [comment]
@camaya7 that is a good point, although there's more to a model than just the weights, also the architecture (like how many layers) and preprocessing (like mapping of words to integers before embedding) parameters are needed.
We are indded considering also the possibility to split the model in multiple files/directories, in that case the path would make sense.
Will keep you posted as we progress!

**Comment by camaya7** [comment]
@w4nderlust Right, I'm confident you can figure out a cohesive solution. Splitting the model sounds promising, a more modular approach would allow for greater future model adaptability-flexibility on a potentially distributed basis. 

I look forward to seeing the outcome, your work is very admirable!
