### ISSUE TITLE
TypeError: Failed to convert object of type <class 'list'> to Tensor.

### ISSUE THREAD

**Issue by Bhavesh-Joshi** [ludwig-ai/ludwig#1070]
**Describe the bug**
An error occurred while saving model with method **save_savedmodel**

**TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [None, -1]. Consider casting elements to a supported type.**

**To Reproduce**
1. Go to 'https://gist.github.com/Bhavesh-Joshi/4db376e4aa6a2ef808c4e54618acc987#file-vqa_train-py'
2. Run vqa_train.py
3. See an error

**Expected behavior**
The model should be saved.

**Environment :**
 - OS: Ubuntu
 - Version 20.04.1 LTS
- Python version 3.6
- Ludwig version 0.3

**Additional context**
Just want to add one scenario which I observed is the error only occurred when I train the model with the image dataset. With another kind of data like text, numbers it works fine.

**Comment by w4nderlust** [comment]
Thanks @Bhavesh-Joshi will look into it.

**Comment by jimthompson5802** [comment]
@Bhavesh-Joshi   I wanted to follow-up with you re: the error you encountered.  First thank for the information you provided.  Using that information  I was able to receate the error you are seeing.  Although I'm still doing research into root cause to figure out a fix, I wanted to provide you a quick status update.  

Lastly, thank you for taking the time to report the issue and helping us improve Ludwig.

**Comment by jimthompson5802** [comment]
@Bhavesh-Joshi  I forgot to ask in the previous posting, if it is possible to get a copy of the image you used `Antenna.jpg`?

**Comment by Bhavesh-Joshi** [comment]
![Antenna](https://user-images.githubusercontent.com/29869080/104283455-8ff71000-54d6-11eb-9cce-32868b9c637c.jpg)

Thanks for the update the @jimthompson5802. Please find the attached Antenna.jpg
