### ISSUE TITLE
Importing the output of the best model

### ISSUE THREAD

**Issue by sabersf** [ludwig-ai/ludwig#1100]
**Describe the use case**

The output of the optimal model is stored in the "model" folder. It includes the model_weight files as well as the training checkpoints. Now I'd like to import that model in a different project and use them as the initial input for that model. It would be nice if you could provide an example for that.

**Describe the solution you'd like**
An example in the example folder that loads the output of ludwig optimal model and use them as initial point in a separate project.

**Comment by w4nderlust** [comment]
If by output you mean "the best set of weights over the course of training" like I believe, and if by initial input you actually mean "initial weights or weight initialization", the way to load it is very simple:
```
my_model = LudwgiModel.load(model_path"
```
And then you cna use `my_model` to do what you want, like fine tuning on another dataset or using it for prediction.
Was this helpful? Otherwise please give me a bit more context so that I can understand better ;)

**Comment by sabersf** [comment]
Thanks, that answered my question. I wanted to import the model into a TF model but that works as well.
