### ISSUE TITLE
Adding probability to the available datatypes

### ISSUE THREAD

**Issue by sabersf** [ludwig-ai/ludwig#1102]
It would be great if you could add probability type to the available datatype.

**Comment by w4nderlust** [comment]
Curious to hear about the usecase.
I imagine that for inputs there would be no difference with numerical, but maybe you are thinking at the output so that you can provide a probability as supervision and optimize with cross entropy?

Right now you actually have a workaround of using a vector feature and using crossentropy, but I see how having a probability type may make things mroe straightforward.

**Comment by dalianaliu** [comment]
Hi @sabersf, closing this for now. Please re-open if you have more comments on this request.
