### ISSUE TITLE
visualize.learning_curves() error

### ISSUE THREAD

**Issue by ZaneL** [ludwig-ai/ludwig#1106]
When using ludwig-0.3.3 on Kaggle, I get this error when running `visualize.learning_curves([train_stats],None)`:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-f14b4201dd4f> in <module>
     25 
     26 from ludwig import visualize
---> 27 visualize.learning_curves([train_stats],None)

/opt/conda/lib/python3.7/site-packages/ludwig/visualize.py in learning_curves(train_stats_per_model, output_feature_name, model_names, output_directory, file_format, **kwargs)
   1283     output_feature_names = _validate_output_feature_name_from_train_stats(
   1284         output_feature_name,
-> 1285         train_stats_per_model_list
   1286     )
   1287 

/opt/conda/lib/python3.7/site-packages/ludwig/visualize.py in _validate_output_feature_name_from_train_stats(output_feature_name, train_stats_per_model)
    115     output_feature_names_set = set()
    116     for ls in train_stats_per_model:
--> 117         for _, values in ls.items():
    118             for key in values:
    119                 output_feature_names_set.add(key)

AttributeError: 'tuple' object has no attribute 'items'
```

This same code ran perfectly fine back in 2019 when using an older version of Ludwig. I haven't changed my code at all.

**Comment by jimthompson5802** [comment]
@ZaneL Starting with v0.3, there were many breaking changes.  Here is [the link](https://ludwig-ai.github.io/ludwig-docs/api/visualization/#learning_curves) to the current `learning_curves()` api doc.

I recommending looking over the updated documentation to see what other changes may be required in your code.

If after making changes to your code for v0.3.x, you still are experiencing problems, please post your code and any other relevant information so we can help you.

**Comment by ZaneL** [comment]
I don't know what could be wrong. I've looked at the breaking changes and I think I'm still doing everything correctly.

```
from ludwig.api import LudwigModel

model = LudwigModel(config)
train_stats = model.train(training_dataframe)

from ludwig import visualize
visualize.learning_curves(train_stats_per_model=[train_stats])
```

This code is still throwing that same error in the visualize function.

**Comment by jimthompson5802** [comment]
@ZaneL   Let me refer you to the [updated API doc for `train()`](https://ludwig-ai.github.io/ludwig-docs/api/LudwigModel/#train).  If you scroll down to where the return is described, you'll see that `train()` returns a tuple of three data structures:
<img width="716" alt="image" src="https://user-images.githubusercontent.com/1425269/109085397-91237b80-76d7-11eb-8f73-241de337b9be.png">

So your code 
```
train_stats = model.train(training_dataframe)
```
This means that `train_stats` is a tuple containing `(training_statistics, preprocessed_data, output_dictionary)`.  So when you code
```
visualize.learning_curves(train_stats_per_model=[train_stats])
```
you are passing a tuple to the `learning_curve()` method not a `training_statistics` dictionary as the api doc describes.
<img width="689" alt="image" src="https://user-images.githubusercontent.com/1425269/109085750-448c7000-76d8-11eb-8080-d5a47d11eb0c.png">

There are couple of ways to address the situation:
#### Method 1  `train_stats, _, _ = model.train(....)`
#### Method 2 `visualize.learning_curves(train_stats_per_model=[train_stats[0])`

Either method should address the immediate issue with `learning_curve()`, though I prefer `Method 1` because it is more explicit.

Let me know if this helped or not.

**Comment by ZaneL** [comment]
That worked perfectly, thank you!

```
from ludwig.api import LudwigModel

model = LudwigModel(config)
train_stats, _, _ = model.train(training_dataframe)

from ludwig import visualize
visualize.learning_curves(train_stats_per_model=[train_stats])
```

and then to predict...

```
predictions, _ = model.predict(predict_dataframe)
```
