### ISSUE TITLE
How to use trained model in Golang?

### ISSUE THREAD

**Issue by stremovskyy** [ludwig-ai/ludwig#1156]
How to use trained model in Golang?

I have several trained models and application written on Golang
Now I have used several instances “ludwig serve” and send requests to it
Is three any way to use this models in Golang program directly?

**Comment by jimthompson5802** [comment]
@Karmadon Thank you for submitting this question.

As of this point Ludwig supports only Python bindings.

I'll mark your questions as potential feature request.   At this point, however, it is not in scope.

**Comment by Karmadon** [comment]
@jimthompson5802 Thx for your work!

**Comment by tgaddair** [comment]
Hey @Karmadon, one option for you would be to export your Ludwig model to a [Neuropod](https://github.com/uber/neuropod), which we have an API for [here](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/export.py#L59).

Once exported to Neuropod, you can use its [C++ API](https://neuropod.ai/docs/stable/cppguide/) in conjunction with [cgo](https://golang.org/cmd/cgo/) to perform inference on the Ludwig model from your Golang application. This approach was what we used to perform inference on Ludwig models from Go at Uber.

**Comment by Karmadon** [comment]
Thank you @tgaddair ! I will try this way,
Where to find c bindings for neuropod? or are they not in the public repos?

**Comment by tgaddair** [comment]
@vkuzmin-uber @VivekPanyam are there still plans to add Golang bindings to Neuropod?

I see there's this issue that is still open: https://github.com/uber/neuropod/issues/294

Any updates?

**Comment by VivekPanyam** [comment]
Hi! Sorry for the delay; the last few weeks have unfortunately been quite taxing

@Karmadon The C API is [here](https://github.com/uber/neuropod/blob/master/source/neuropod/bindings/c/c_api.h) and here's a [test](https://github.com/uber/neuropod/blob/a7c36633e75e4d99eb94961f22131c19e404b068/source/neuropod/bindings/c/test/test_c_api.c#L56) that shows example usage

In order to use it, you'll need at least Neuropod [v0.3.0-rc1](https://github.com/uber/neuropod/releases/tag/v0.3.0-rc1). Installation instructions are [here](https://neuropod.ai/docs/master/installing/).

@tgaddair I'm not sure what the status of that is. @vkuzmin-uber or @thuningxu would probably know better

**Comment by Karmadon** [comment]
@VivekPanyam  Thank you so much! It looks like this is exactly what I need. I will try to write POC. If it works, I will definitely share it.

**Comment by dalianaliu** [comment]
Hi @Karmadon, just want to follow up to see if you have used it for your POC?
