### ISSUE TITLE
Address issue that Ludwig often reports root_mean_squared_error_percentage being infinity

### ISSUE THREAD

**Issue by amholler** [ludwig-ai/ludwig#1281]
This seems to be happening when target value is 0, due to divide by 0.  One example is trial_9b499_00018
in Sarcos/Hband/Tabconcat.

Piero and I discussed this; his comments:
>Regarding RMSPE. It's a nasty issue and there's no consesus, see here:
>https://stats.stackexchange.com/questions/86708/how-to-calculate-relative-error-when-the-true-value-is-zero
>That said, I belive hasing a max(epsilon, abs(y)) as the denominator instead of y is a very reasonable choice.

Also, AFAICT we aren't multiplying the overall result by 100.0 to convert to percent FWIW.

**Comment by w4nderlust** [comment]
RMSPE numerical stability t's a nasty issue and there's no consesus, see here: https://stats.stackexchange.com/questions/86708/how-to-calculate-relative-error-when-the-true-value-is-zero
That said, I believe hasing a `max(epsilon, abs(y))` as the denominator instead of `y` is a very reasonable choice.
