### ISSUE TITLE
Is ludwig video course available?

### ISSUE THREAD

**Issue by PeterPirog** [ludwig-ai/ludwig#1510]
I would like to ask if there is some ludwig course available online free or paid?
I know that there is documentation but sometimes I prefer video step by step tutorials.

**Comment by w4nderlust** [comment]
@PeterPirog unfortunately we don't have a video course right now, but that's a great idea!
There are some videos and blogposts that could serve as good introductions though.
Here are a few:
- Basic introduction video: https://youtu.be/OGweVw57kus 
- Full 1h presentation: https://youtu.be/xuMx-Dmdico  (it's a bit outdated, will soon record a new one after we release v0.5)
- Sentiment analysis tutorial (training from scratch): https://medium.com/ludwig-ai/the-complete-guide-to-sentiment-analysis-with-ludwig-part-i-65a9e6bc054e
- Sentiment analysis tutorial (fine-tuning): https://medium.com/ludwig-ai/the-complete-guide-to-sentiment-analysis-with-ludwig-part-ii-d9f3952a06c6
- Sentiment analysis tutorial (hyper opt): https://medium.com/ludwig-ai/hyperparameter-optimization-with-ludwig-6e31272e43fb

Hopefully these could be good starting points. Let me know if you have feedback!

(also, transforming this into a discussion rather than an issue)
