### ISSUE TITLE
Using Sequence Feature Encoders with pretrained embeddings from huggingface

### ISSUE THREAD

**Issue by smiraldr** [ludwig-ai/ludwig#1832]
As mentioned on https://ludwig-ai.github.io/ludwig-docs/0.4/configuration/features/sequence_features/#embed-encoder
We can use pretrained embeddings in glove format for sequence encoders. Is there any way we could use the pretrained transformer models with sequence encoder from huggingface directly incase glove format is not available? 
I've already tried using hf_tokenizer for text feature on word level but i'm looking to use it with sequence encoder.
Would appreciate if anyone could help me out.

**Comment by w4nderlust** [comment]
Pasting here the answer from the Ludwig Slack:

There’s a misunderstanding of what word / character / sequence / text / embedding mean in Ludwig. Let me try to give you context :wink:
Text and Sequence are identical in Ludwig, the only difference is the encoders and tokenizers available. What happens in both text and sequence is that the input string is tokenized into tokens. In the case of sequence, whitespace is the default tokenizer, for text you have several more options. Glove embeddings can be provided to both text and sequence features to define how to encode each token that is the output of the tokenizer. So the GloVe embeddings (or any set of embeddings obtained by any algorithm and saved in GloVe format) are used as first embedding layer in all encoder models (parallel_cnn, rnn/lstm/gru, transformer) for both text and sequence. The difference is that text also allows you to use pretrained transformers. The way to use them is to just specify the encoder, for instance gpt2. The preprocessing parameters (including the tokenizer, the vocabulary and others) associated with gpt2 will be automatically used, you don’t have to specify anything else in preprocessing. The output of the text encoder loaded from these pretrained models will be a vector (“sentence embedding” if you want, although i don’t like using the word embedding for the output of encoders because it has a very different meaning from the meaning of “embedding layer” where each embedding is a set of weights in an embedding matrix). That vector will be used down the line to perform a task.
So Ludwig provides already a bunch of text encoders obtained from these pretrained models, like bert, gpt2, roberta, t5, etc. The Autotransformer encoder that I was suggesting allow you to specify the bath of the transformer model on disk or it’s name like you would provide to huggingface to obtain it, and use it directly 8again the associated tokenizer will automatically be used).
Does this help?
