### ISSUE TITLE
Feature request: GAN support

### ISSUE THREAD

**Issue by bitcoinmeetups** [ludwig-ai/ludwig#198]
Hello,

Does Ludwig support GAN's?

How about a feature where the user inputs a list of images and receives as output a bunch of cool GAN generated images?

BM

**Comment by w4nderlust** [comment]
Well at prediction time you don't need to provide anything, you just sample from noise and you produce images from there :)
Anyway, yes it's on out list, there needs to be a little piece before it, the image output feature so that first Ludwig can output images, then we can add a loss that is a GAN loss which contains also a discriminator.
More thought needs to be put into it, but it's definitely something that we eventually want to support.

**Comment by sk1210** [comment]
Hi @w4nderlust , I would like to work on adding this feature, Can you guide me in that, like how to start or any reference.

**Comment by bitcoinmeetups** [comment]
Awesome @w4nderlust!

Following this!

**Comment by w4nderlust** [comment]
@sk1210 the first step would be to implement an image output feature, with a way to produce an image (deconvolution for instance), a way to calculate loss and a way to compute measures.
I would use the `cetegory_feature.py` module as a template to copy from.

**Comment by EdwardFKit** [comment]
Has there been progress on this - this would be of great use!

**Comment by w4nderlust** [comment]
@EdwardFKit this is currently not being worked on, there after the release of v0.3 (a month or so), we will reasses all users requests to rigure out priorities for v0.4 But we did not forget about this, it's just that with the resources at our disposal, it has not been prioritized yet.

**Comment by sk1210** [comment]
@w4nderlust, @EdwardFKit  I have now started working on this, I will keep you updated.

**Comment by EdwardFKit** [comment]
Great – please do – FYI what we are working on is not image / gradient based – it is more related to NLP / Keyword / Phrase / special purpose text generation – basically to generate automated Keyword software test cases for software systems -

**Comment by w4nderlust** [comment]
> @w4nderlust, @EdwardFKit I have now started working on this, I will keep you updated.

@sk1210 that sound great, thank you for being willing to help, that is hreatly appreciated.
Assing GANs to Ludwig is non trivial at the moment because of its architectures. Some of the changes we are making for v0.3 will definitely make it easier.
Because it's non trivial I suggest you to fisrt study in detail the codebase, the best way being training a model by going through it with a debugger, line by line.
After you have done that, you can come un with a design proposal and we can discuss together about it. For it to be something I woyld want to include in the codebase, it will need to be a generic solution. So I encourage you to get in touch before steaming ahead and implementing things to avoid the risk you'll come up with a solution I would not want to include.
Does this make sense to you?

**Comment by fire** [comment]
Stable diffusion and clip interrogator now exist.

Can be used to make a GAN image loop.

1. provide image, and prompt/negative prompt
1. run clip interrogator to generate prompt text
1. generate image with prompt text
1. goto the start
