### ISSUE TITLE
Can you train a Ludwig model on Google Cloud ML Engine?

### ISSUE THREAD

**Issue by Aashish-1008** [ludwig-ai/ludwig#208]

**Comment by w4nderlust** [comment]
I have never tried, I'm not sure what is required to be able to do that. Let's see if someone has tried to do it.

**Comment by Aashish-1008** [comment]
I will try to use lugwig on Google Cloud ML Engine and host the model in cloud ml engine.
Hope it works.

**Comment by dawhudlaide** [comment]
I am currently doing sentiment analysis for reviews data. I already have my model on the localhost. I'm currently trying it out on GCP hopefully it works.

**Comment by gogasca** [comment]
In order to train a Ludwig model, you need to create a folder structure and Python code which is compatible with Cloud ML Engine format. (Check example [here](https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/cloudml-template/examples/classification/census))
If Ludwig generates a [SavedModel] after training (https://www.tensorflow.org/guide/saved_model#build_and_load_a_savedmodel) format, you can yoy configure Serving in Cloud ML Engine.
