### ISSUE TITLE
Question: is path_to_best_model same to hyperopt_tabnet/model?

### ISSUE THREAD

**Issue by Jeffwan** [ludwig-ai/ludwig#2409]
After a hyperopt job, I can get `auto_train_results`. One thing is a little bit confused. I found two paths for the best persisted model.

1. auto_train_results.path_to_best_model -> hyperopt/trail_63dfb25e/checkpoint_000360.
2. after I get the best trail id, I find the artifacts associated with trail, in this case, model is `hyperopt/trail_63dfb25e/hyperopt_tabnet/model`

Seem these two models are exact same? the only different file is `training_progress.json`. Not sure if it's because there's a `checkpoint_000361` (not the best model) so  `training_progress.json` in `hyperopt_tabnet/model` is different? 

Can someone help explain more details on the difference?

![image](https://user-images.githubusercontent.com/4739316/185842022-e00f4d3d-ccb8-4a64-b4ce-c0681c1e9ee6.png)

**Comment by arnavgarg1** [comment]
Hey @Jeffwan, thanks for the great question! I'm looking into this and will respond back with an answer soon. 

I wanted to ask some clarifying questions:

- Is `hyperopt_tabnet` the experiment name?
- Are you able to share your config?

From my understanding, these are actually identical. The top-level `hyperopt_tabnet/model` is something Ludwig internally saves as artifacts, while the items from `trial_X/checkpoint` come from RayTune's sync client writing locally. We're working on cleaning this up so that we don't log the same artifacts in multiple places.  cc: @ShreyaR 

As for the `path_to_best_model`, this is actually picked up the ExperimentAnalysis object that RayTune returns internally, which picks up the best model from the `trial_X/checkpoints` folder since those are the paths that RayTune uses. 

Hope this helps!

**Comment by Jeffwan** [comment]
Sorry for late response.

> Is hyperopt_tabnet the experiment name?
no, I didn't specify any experiment name

> Are you able to share your config?
Here it is. 
[config.yaml.zip](https://github.com/ludwig-ai/ludwig/files/9571444/config.yaml.zip)



BTW, seems `path_to_best_model ` is removed in master now. I am using `auto_train_results.experiment_analysis.best_checkpoint._local_path` now.

**Comment by arnavgarg1** [comment]
@Jeffwan 

> Is hyperopt_tabnet the experiment name?

Got it! I think we might default to that from Ludwig internally

A couple of things I wanted to share:

1. I was actually wrong about the checkpoint weights and the model weights in `/hyperopt_tabnet` are equal. The weights in `/hyperopt_tabnet` are actually from Ludwig and are updated every time we run evaluation. The weights in `checkpoints` are saved based on the performance of that evaluation round. In particular, when you get the best_checkpoint, the weights for the `best_checkpoint` will likely not be equal to the weights in `hyperopt_tabnet` because the best_checkpoint might be for an earlier evaluation for an earlier epoch because the model may have started overfitting. My recommendation would be to use the weights from the best checkpoint.
2. That's correct, the latest master has made some changes that removed `path_to_best_model`. In a PR I'm working on, I'll be adding some more properties to get the `best_checkpoint`, `best_checkpoint_cloud_path` and `best_checkpoint_local_path` so that this is easier rather than having to nest through the auto_train_results in the way you're having to at the moment.

Hope this helps!

**Comment by Jeffwan** [comment]
Sounds good. It would be great to see new properties are added soon. I am good on my side and let me close the issue
