### ISSUE TITLE
`ludwig-dev` Dockerfile still uses Tensorflow

### ISSUE THREAD

**Issue by arnavgarg1** [ludwig-ai/ludwig#2872]
These Docker images need to be updated to use PyTorch instead of Tensorflow as the base image. It might also requires updates to other dependencies within the Dockerfile.

**Comment by tgaddair** [comment]
The `ludwig` image uses a base python image: https://github.com/ludwig-ai/ludwig/blob/master/docker/ludwig/Dockerfile#L12

The `ludwig-dev` image is indeed incorrect. Maybe we can just remove it, since it's clearly broken, and direct people to checkout the [devcontainer](https://github.com/ludwig-ai/ludwig/blob/master/.devcontainer/Dockerfile) image instead in the docs.

**Comment by arnavgarg1** [comment]
PR: https://github.com/ludwig-ai/ludwig/pull/2873
