### ISSUE TITLE
this project support windows?

### ISSUE THREAD

**Issue by futureflsl** [ludwig-ai/ludwig#3657]
I try to install:
pip install ludwig,it error on windows10 x64,it seems that getdaft cannot support on windows.

**Comment by tgaddair** [comment]
Hey @futureflsl, thanks for reporting this issue. We do support Windows by design, however, one of our more recent dependencies currently doesn't publish Windows wheels (https://github.com/Eventual-Inc/Daft/issues/235), which had led to this issue. We're chatting with the maintainers of Daft and they said they should have Windows wheels officially supported soon (next week or two at worst, I suspect).

As a workaround for now, there are a few options:

- Install Ludwig from the `master` branch, which now includes this fix: #3629, which skips trying to install `getdaft` on Windows. The only downside of this is that currently using Image input features requires Daft. So if you're not using Ludwig with images, this is the easiest option.
- Try installing Daft from source with experimental Windows support. They're working on adding prebuilt wheels to their CI system, but it sounds like it should be working if you install from source.
- Revert to Ludwig 0.7 (before we added the Daft dependency), but this would not have support for our more recent LLM features.

**Comment by tgaddair** [comment]
Hey @futureflsl, now that Daft is publishing Windows binaries, this issue should be resolved. Let me know if you continue to run into issues running on Windows.
