### ISSUE TITLE
GPU is not available

### ISSUE THREAD

**Issue by LittleStarrider** [ludwig-ai/ludwig#3972]
Hello everyone.

First of all, I'm very new to training and fine-tuning LLMs, so my problem could be very straight forward (or not). Also forgive me in andvance for not knowing stuff.

System:
Windows 11
Python 3.10
Ludwig 0.10

I created a virtual environment locally and then pip installed ludwig. My propertys.yaml file also seems to cause no issue, as the model loads just fine.

I tried to model.generate() on a locally downloaded model from HF, just to see if it generates some kind of output. But I only get this error:

```
PyTorch version 2.2.1 available.
C:\Users\Name\OneDrive\Dokumente\Python\Tetera\Tetera\.venv\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "

'NoneType' object has no attribute 'cadam32bit_grad_fp32'
Setting generation max_new_tokens to 16384 to correspond with the max sequence length assigned to the output feature or the global max sequence length. This will ensure that the correct number of tokens are generated at inference time. To override this behavior, set `generation.max_new_tokens` to a different value in your Ludwig config.

Traceback (most recent call last):
  File "C:\Users\fabio\OneDrive\Dokumente\Python\Tetera\Tetera\app.py", line 7, in <module>
    print(model.generate("Hello World"))
  File "C:\Users\fabio\OneDrive\Dokumente\Python\Tetera\Tetera\.venv\lib\site-packages\ludwig\api.py", line 990, in generate
    raise ValueError("GPU is not available.")
ValueError: GPU is not available.
``` 

Do I have a problem with bitsandbytes? Or is it torch?
```torch.cuda.is_available()``` also returns false.

Or do I have to create an Anaconda3 environment? I tested it there and installed pytorch via conda install and then ```torch.cuda.is_available()``` returns true. But Ludwig seems to not work in this environment.(?)

I am thankfull for any help. My goal is to get this thing at least running.

**Comment by frhazman** [comment]
It seems you're having trouble getting your GPU to work with PyTorch. I'm using A770 so it works fine on my side. Here's a more direct approach to fix this:

Make sure your graphics card driver is up to date.
 PyTorch needs the right CUDA version and can check the PyTorch installation guide here - https://pytorch.org/get-started/locally/ to pick the build that matches your CUDA version.

Since the warning suggests it lacks GPU support. Follow this doc https://github.com/TimDettmers/bitsandbytes to install a GPU-compatible version.
 For environment setup, while Anaconda can simplify package management, it's not a must. Whether you use pip or Conda, ensure you're installing packages with GPU support.

Oh also, Intel provides optimization tools that can help improve the performance of AI applications on Intel hardware. Can refer Intel Optimization for PyTorch on https://www.intel.com/content/www/us/en/developer/tools/oneapi/optimization-for-pytorch.html#gs.clz6p0, which is designed to accelerate PyTorch performance on Intel processors.

If torch.cuda.is_available() is still False, your system might not be fully compatible with CUDA, or there's an issue with the GPU setup.

Hope this can help you.

**Comment by alexsherstinsky** [comment]
The issue is with the environment (CUDA is not available).
