### ISSUE TITLE
Support for External Data Sources

### ISSUE THREAD

**Issue by oelesinsc24** [ludwig-ai/ludwig#54]
Would it be possible to have S3 or any other object storage support? E.g reading input data from S3 or saving model to S3.

I know there could be a workaround using [S3FS](https://s3fs.readthedocs.io/en/latest/), but is this supported outta-the-box?

Thanks

**Comment by w4nderlust** [comment]
Haven't thought about it yet. I think data connectors will be one of the main required features.
We are considering using [Petastorm](https://github.com/uber/petastorm) in future releases, so looking at [this](https://github.com/uber/petastorm/issues/210) it should support S3, so that would cover your use case.

**Comment by oelesinsc24** [comment]
Thanks

**Comment by signupsi** [comment]
it might be good idea to support common protocol so that products like Minio / ceph can be integrated  without integrating petastorm 
Petastorm is great gateway  using parquet format.

however adoption will be relatively easier if the ludwig could connect directly to  has been using ceph , minio, s3 etc

**Comment by ifokeev** [comment]
I have code-integration with MLFlow that want to contribute soon. I'm using it with `Minio`, by the way.

@oelesinsc24 do I need to wait until TF2 branch merged? Will it has breaking compatibility?

**Comment by w4nderlust** [comment]
@signupsi there's a n [open branch](https://github.com/uber/ludwig/tree/preprocessing_strategy) where i started sketching a preprocessing reoranization through a strategy pattern that will allow different pluggable modules for each format / datatype / source. You can see an example [here](https://github.com/uber/ludwig/blob/preprocessing_strategy/ludwig/data/preprocessing.py#L1170-L1197). It's still work in progress, and will be one of the main foci of v0.3 . At that point I'll add a section to the developers guide about adding a new preprocessing strategy / connector, so that anyone who has a specific need will be able to contribute it.

"ifokeev , yes I would hold on that a little, first let's finish the TF2 port, and then let's create a PR for that, because otherwise we could spend work integrating it and having to redo a lot of stuff again.

**Comment by signupsi** [comment]
@w4nderlust sounds perfect to enable the ability to add source as per specific format. 
ppl can work with interchangable data using parquet/petastorm or interchange and optionally can use disparate sources as per need.

**Comment by ifokeev** [comment]
@signupsi there are 2 branches about `petastorm` now https://github.com/uber/ludwig/branches, but I believe all this work should be stopped until tf2 upgrade =\

Also I think Ludwig needs a stable maintainers core. That's already too much tasks for 1-3 people. It needs 2-4 engaged developers.

**Comment by w4nderlust** [comment]
Those branches were several different attempts, they will be deleted once a final implementation is deemed worthy. That stuff is pretty much independent from TF2 at the moment, so @msaisumanth is working on it in parallel. Regarding maintainer, at the moment there's @msaisumanth , @ydudin3 and me, but yeah there's a lot work to do and having more people involved would be great.

**Comment by justinxzhao** [comment]
Ludwig datasets supports [reading from S3](https://ludwig-ai.github.io/ludwig-docs/0.5/developer_guide/add_a_dataset/).
