### ISSUE TITLE
Training a model with multiple input files

### ISSUE THREAD

**Issue by BY-hash** [ludwig-ai/ludwig#572]
Hello, 
I have traind a model with a .csv input file, and I'm trying to keep training the model with many other input files (each file contains small amount of data, and I have tons of files like this. Also, their structure is important so combining them to one file with a lot of data would lose the structer I want).
After I have sucssesfully traind a model with the first of many .csv file, I would like to keep training the same model with the other files. 
I've seen in isse #71 that --model_load_path is better for me, so for example I tried
ludwig train  --data_csv C:/Users/user/Desktop/DataSet/SecondInputFile.csv --model_load_path C:/Windows/System32/results/experiment_run_12 (the path to the model that have been created by training with the first input file)
but I get the error "ludwig train: error: one of the arguments -md/--model_definition -mdf/--model_definition_file is required".
I have tried many other constallations and none of them works.

Thank you for your help!

**Comment by msaisumanth** [comment]
@BY-hash you just need to provide the model definition that you used to train the model with the first file, right? that'll fix this error.

**Comment by BY-hash** [comment]
Thank you, 
one thing is not clear to me though: if I'm loading an existing model, why should I also provide the model definition again? Shouldn't this information already exist in the model I'm loading?

**Comment by msaisumanth** [comment]
yeah, that's a fair point. We should be able to load the model definition from the folder. I'll mark this as an enhancement.

**Comment by w4nderlust** [comment]
> Thank you,
> one thing is not clear to me though: if I'm loading an existing model, why should I also provide the model definition again? Shouldn't this information already exist in the model I'm loading?

The reason is that ludwig has to re-build the model graph for loading its weights, and it does it from the model definition. If you use `--model_load_path' the model definition could be slightly different from the ones you are loading (for instance you use the same model, but a different last layer to obtain a different classsification). To allow for those cases in the future, we made it so that you also have to specify the model definition. In your case the model definition is anyway present in the same directory you saved the model in, so it should be easy to locate and use it.
