### ISSUE TITLE
Code extraction 

### ISSUE THREAD

**Issue by atwahsz** [ludwig-ai/ludwig#643]
Ludiwg is a fantastic toolbox

How ever it would be amazing that the code or functions called while running can be extracted as a solid code , this will help users to develop their coding skills and maybe provide improvements in the long run ?

**Comment by w4nderlust** [comment]
Thanks @atwahsz !

I'm not really sure what do you mean by "extracted". I guess what you mean is making Ludwig write the code of the model somewhere isntead of executing it. I'm not sure how that will improve things, it would be an additional level of indirection that would make testing things more complicated. Plus, if users want to learn by looking at how a model is built they can look at the code or even better put a breakpoint at the beginning of the build function and follow the trace to see how a model is built. I don't think generating code would make things easier.
In front of a strong argument i could change my mind :)

**Comment by atwahsz** [comment]
Ok then . What about automating model definition? Is there a way ?

**Comment by atwahsz** [comment]
Or is there a way defining a feature and the definition can only be used if the feature exists

**Comment by w4nderlust** [comment]
For automatic model definition, I was thinking along the lines of a recommender, something where you provide the data and it suggests the types, but I didn't follow up on that a lot, because I believe specifying types is not that big of an issue for the user to be honest. And also, having to prioritize, this never made it to the top of the list.

Regarding the second question, if i get it correctly, that's how Ludwig already works. You have image encoders, set encoders, audio encoders among others, but if you specify a text input only, all the others, although available to you, are not going to be used. But maybe i'm misunderstanding what you are asking, please clarify with one example in case.
