### ISSUE TITLE
Feature Request: Add Features at Runtime

### ISSUE THREAD

**Issue by JackyP** [ludwig-ai/ludwig#70]
Currently adding a new feature / encoder / decoder requires forking the package. 

It would be awesome to be able to add them at run time as part of the API and/or a conf.py e.g.

```python
ludwig.add_base_feature(NotNumericalBaseFeature)
```

**Comment by w4nderlust** [comment]
Can you explain a little bit your use case? And why in your case that would be preferable over forking?

Anyway, it is relatively easy to add this capability, features are just collected in a dictionary registry, so one would just have to add to that registry and it will work, as long as the class implementing the feature respects the input / output interface. The only problem I see with it is that at the moment we just expose `LudwigModel` as our API, in order for what you propose to work we would have to expose also other things like `BaseFeature`, `BaseInputFeature` and `BaseOutputFeature`, as the would need to be used when creating you custom feature. I have to think about the pros and cons of such a choice.

Finally, i'm curious, what additional feature type are you implementing? Would you consider contributing it?

**Comment by JackyP** [comment]
Thanks for the quick reply and interest!

By way of background, I work as an actuary in general insurance which includes motor insurance. Many actuaries have statistical and insurance knowhow but often coding is not our specialty and some do not code at all. As a member of a working group with the Institute of Actuaries of Australia looking at data analytics, I am interested in anything that can help our members model insurance data such as insurance claims better or easier. 

When I came across your package, I could see great potential in this tool for actuaries in two contexts:
* Using the no-coding philosophy for non-coding actuaries (albeit, many of those would prefer having a GUI)
* As a set of convenience functions for more data-science oriented actuaries for quickly setting up a model for predicting anything with anything

However, some things I'm thinking are:
* Insurance claims follow distributions like Poisson, Gamma - for those it would make sense to just add the loss to the NumericalBaseFeature and contribute back.
* I have been experimenting with some unusual actuarial claim model structures which might not be of general interest and planning to write a python package for it to go with a paper - I had started writing up some convenience functions that are similar in concept as yours but much less developed so I am considering whether it would be worthwhile to pivot to use your package instead and build on a stronger base.

Having the extensions as part of the API would mean that I can have it as a dependency rather than either maintaining a fork of your codebase or attempting to persuade you to accept a PR that is oddly specific. Also, it means actuaries with only intermediate python knowledge and no other dev skills can pip install, import and customise it in jupyter without having to know git.

**Comment by w4nderlust** [comment]
Thanks for the explanation @JackyP !
Your use case is really interesting, keep me posted about it.

Regarding contributing additional numerical losses, you are more than welcome to do that. the numerical output feature deserves more love, but as i don't have many use cases for it myself at the moment, it is lagging behind, but the reason for open sourcing this tool is exactly so that people can just add what they need and do not care about all the rest, so a contribution would be perfect.

Regarding the motivation for having features added dynamically, I see your point. I still feel that, even if they are niche contributing them would be great, but I see how a mechanism for adding them may be beneficial. So we will consider this enhancement for the future releases.

**Comment by rolisz** [comment]
Another use case for this: I would like to add support for MRI data for Ludwig. I think this is a very niche feature, so it won't be useful for too many people. I managed to implement it, but the documentation was a bit lacking, so it was a process of running, seeing which dictionary didn't have the new key and updating it. In particular, because I added the new InputFeature outside of Ludwig, the `default_preprocessing_parameters` in `utils/defaults.py` didn't contain the parameters for the MRI feature and I had to update it manually.

**Comment by w4nderlust** [comment]
You shouldn't add the parameters to default preprocessing parameters in default, but you should crete a BaseFeature and inherit from it. Look for instance at the simple binary feature BaseFeature: https://github.com/uber/ludwig/blob/master/ludwig/features/base_feature.py#L26
It contains the preprocessing paramters for this specific features in the init.

Anyway, admittedly the Developer guide needs more work to be a super useful resource, we'll be working on it to make contributions easier. If you want to distill what you learned from your experience by adding something to developers guide, that would be much appreciated (just add stuff to `mkdocs/docs/developer_guide.md` and make a PR.

Finally, I believe fMRI could potentially be generalized to a more generic concept of 4d tensors, and may work for instance for videos. The same models that you use for fMRI can be used for videos too, so I wouldn't discard the idea of adding that as a main datatype. You may potentially do a PR and if it's not general enough I can work on top of that to generalize it. I would be really glad for that :)

**Comment by justinxzhao** [comment]
The developer guide has been revamped -- please check https://ludwig-ai.github.io/ludwig-docs/latest/developer_guide/add_a_feature_type/ to learn how to implement a new feature type in Ludwig.
