### ISSUE TITLE
Category feature question?

### ISSUE THREAD

**Issue by theodor38** [ludwig-ai/ludwig#704]
Please look at the following and my question is "is there a way to order the mapping of the category alphabetically rather than based on frequency?

Thank you in advance.

"Input1": {
        "idx2str": [
            "<UNK>",
            "4",
            "3",
            "5",
            "1",
            "2",
            "6",
            "7",
            "8",
            "9"
        ],
        "preprocessing": {
            "fill_value": "<UNK>",
            "lowercase": false,
            "missing_value_strategy": "fill_with_const",
            "most_common": 10000
        },
        "str2freq": {
            "1": 47813,
            "2": 47552,
            "3": 48685,
            "4": 48743,
            "5": 47999,
            "6": 44505,
            "7": 31194,
            "8": 1614,
            "9": 60,
            "<UNK>": 0
        },
        _**"str2idx": {
            "1": 4,
            "2": 5,
            "3": 2,
            "4": 1,
            "5": 3,
            "6": 6,
            "7": 7,
            "8": 8,
            "9": 9,**
            "<UNK>": 0_
        },
        "vocab_size": 10
    }

---------------------------------------------
DESIRED OUTCOME:

       _**"str2idx": {
            "1": 1,
            "2": 2,
            "3": 3,
            "4": 4,
            "5": 5,
            "6": 6,
            "7": 7,
            "8": 8,
            "9": 9,**

I appreciate any help with this :)

**Comment by w4nderlust** [comment]
At the moment there is no mechanism for that, but I'm curious, why do you need it? The predictions you get from `predict` are already mapped back to the original strings anyway.

**Comment by theodor38** [comment]
I think i figured it out. I was just wondering.

Thank you for your response @w4nderlust

**Comment by w4nderlust** [comment]
@theodor38 what did you figure out? If you explain to me your use case, if it makes sense, I can try to incorporate it, but I have to understand the reasons first. Cheers.

**Comment by theodor38** [comment]
@w4nderlust 

I was hoping to use the model directly with TFServing. Which then forces me to manually change back the ordering. It would be great if you could implement an alphabetical ordering for those who wish the use the models in these ways.

**Comment by w4nderlust** [comment]
@theodor38  Got it, i understand the issue, but there is a bigger one, which is the fact that data is preprocessed by Ludwig in python as well as it is postprocessed, which means that when serving the model with TServing you would have anyway to preprocess the data too, as well as postprocessing the model outputs. That's actually what `ludwig serve` does for you (although the model is not served by TFServing, but just loaded in memory).

So adding the alphabetical sorting may solve this specific instance where your labels are numbers, but wouldn't solve the bigger postprocessing issue and not solve the bigger serving issue.

What I would suggest you to do is to use Ludwig's python preprocessing and postprocessing functions and wrap the tf serving around them. If the serving needs to be done in another language  like Java or Go, you can in most cases easily load `train_set_metadata.json` and perform the pre and psot processing.
I know it's not straightforward and requires some work, but that's the best solution so far. I'm considering adding some preprocessing and psotprocessing to the TF graph, so that the TFServing wouldn't need any wrapper, but the problem is that some the processing that I do is pretty elaborate, doing it in the graph would be complicated and I would be restricted in the type of preprocessing I could do, so I did not follow that route so far.

But anyway thank you for the discussion, I'll try to make model serving outside `ludwig serve` more straightforward in the future,

**Comment by theodor38** [comment]
@w4nderlust 

Thank you very much for all the detailed info. You are great!

I pretty much did something similar to what you suggested with wrapping. 

I wish you best of luck with continued development of Ludwig!
Cheers
